"""
Final report builder.

Assembles all pipeline outputs (resume match, transcript, transcript
analysis, facial/eye-contact indicators, AI feedback) into a single
Markdown report that can be downloaded from the Final Report page.
"""

from datetime import datetime


def build_report_markdown(data: dict) -> str:
    candidate_name = data.get("candidate_name") or "Candidate"
    role = data.get("role", "N/A")
    match_result = data.get("match_result", {})
    transcript = data.get("transcript", "")
    transcript_analysis = data.get("transcript_analysis", {})
    facial_result = data.get("facial_result", {})
    eye_contact_result = data.get("eye_contact_result", {})
    feedback = data.get("feedback", {})

    lines = []
    lines.append(f"# AI Interview Analyzer — Final Report")
    lines.append(f"*Generated on {datetime.now().strftime('%Y-%m-%d %H:%M')}*")
    lines.append("")
    lines.append("> This report is an AI-assisted decision-support summary. "
                  "It does not represent a hiring decision. The final "
                  "decision must be made by a human recruiter/interviewer.")
    lines.append("")
    lines.append("## Candidate Information")
    lines.append(f"- **Candidate:** {candidate_name}")
    lines.append(f"- **Target Role:** {role}")
    lines.append("")

    lines.append("## Resume Match")
    lines.append(f"- **Resume Match Score:** {match_result.get('score_pct', 'N/A')}%")
    matched = match_result.get("matched_skills", [])
    missing = match_result.get("missing_skills", [])
    lines.append(f"- **Matched Skills:** {', '.join(matched) if matched else 'None detected'}")
    lines.append(f"- **Missing Skills:** {', '.join(missing) if missing else 'None'}")
    lines.append("")

    lines.append("## Interview Transcript")
    if data.get("transcript_is_demo"):
        lines.append("*[DEMO MODE transcript — Whisper not available in this environment]*")
        lines.append("")
    lines.append(transcript if transcript else "*No transcript available.*")
    lines.append("")

    lines.append("## Answer Analysis")
    lines.append(f"- **Relevance:** {transcript_analysis.get('relevance', 'N/A')}")
    kw = transcript_analysis.get("keywords", [])
    lines.append(f"- **Keywords:** {', '.join(kw) if kw else 'None detected'}")
    lines.append(f"- **Answer Length:** ~{transcript_analysis.get('estimated_seconds', 0)} seconds "
                 f"({transcript_analysis.get('word_count', 0)} words)")
    lines.append(f"- **Filler Words:** {transcript_analysis.get('filler_word_count', 0)}")
    lines.append("")

    lines.append("## Visual Analysis")
    lines.append("*Observed behavioral indicators only — not proof of emotion, "
                 "confidence, honesty, or personality.*")
    dist = facial_result.get("distribution", {})
    if dist:
        for label, pct in dist.items():
            lines.append(f"- **{label}:** {pct}%")
    else:
        lines.append("- No facial-expression data available.")
    lines.append(f"- **Eye Contact (toward camera):** {eye_contact_result.get('eye_contact_pct', 'N/A')}%")
    lines.append(f"- **Looking Away:** {eye_contact_result.get('looking_away_pct', 'N/A')}%")
    lines.append("")

    lines.append("## AI Feedback")
    lines.append("### Strengths")
    for s in feedback.get("strengths", []):
        lines.append(f"- {s}")
    lines.append("")
    lines.append("### Areas for Improvement")
    for i in feedback.get("improvements", []):
        lines.append(f"- {i}")
    lines.append("")
    lines.append("### Recommendations")
    for r in feedback.get("recommendations", []):
        lines.append(f"- {r}")
    lines.append("")

    lines.append("---")
    lines.append("*Generated by AI Interview Analyzer — a decision-support "
                 "prototype. Final hiring decisions remain with the human "
                 "interviewer/recruiter.*")

    return "\n".join(lines)
